'use server'

import { createServerSupabaseClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'

/**
 * Marks a quote as SENT and generates a share token if needed.
 */
export async function sendQuoteAction(quoteId: string) {
  const supabase = await createServerSupabaseClient()
  
  // Verify user is authenticated and get org_id
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    throw new Error('Unauthorized')
  }

  // Check if quote exists and belongs to user's org (RLS handles this but good to be explicit/safe)
  const { data: quote, error: fetchError } = await supabase
    .from('quotes')
    .select('id, status, org_id')
    .eq('id', quoteId)
    .single()

  if (fetchError || !quote) {
    throw new Error('Quote not found')
  }

  // Update status to SENT
  // Note: share_token is auto-generated by default in schema, so we don't need to manually create it
  // unless it's missing. But schema has DEFAULT gen_random_bytes.
  
  const { error: updateError } = await supabase
    .from('quotes')
    .update({ 
      status: 'SENT',
      updated_at: new Date().toISOString()
    })
    .eq('id', quoteId)

  if (updateError) {
    throw new Error(`Failed to send quote: ${updateError.message}`)
  }

  revalidatePath(`/quotes/${quoteId}`)
  revalidatePath('/quotes')
  
  return { success: true }
}

/**
 * Converts a quote to a job.
 * Clones quote data -> jobs, quote_line_items -> job_line_items.
 */
export async function convertQuoteToJobAction(quoteId: string) {
  const supabase = await createServerSupabaseClient()
  
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('Unauthorized')

  // 1. Fetch full quote details including lines
  // We need to fetch sections too if we want to preserve structure, 
  // but job_line_items flattens the structure slightly (source_quote_line_id links back).
  // The schema for job_line_items copies fields from quote_line_items.
  
  const { data: quote, error: quoteError } = await supabase
    .from('quotes')
    .select(`
      *,
      quote_line_items (*)
    `)
    .eq('id', quoteId)
    .single()

  if (quoteError || !quote) throw new Error('Quote not found')

  if (quote.job_id) {
    throw new Error('Quote is already converted to a job')
  }

  // 2. Create Job Record
  // Map Quote -> Job
  const { data: job, error: jobError } = await supabase
    .from('jobs')
    .insert({
      org_id: quote.org_id,
      source_quote_id: quote.id,
      client_id: quote.client_id,
      title: quote.reference || `Job from Quote ${quote.id.slice(0, 8)}`,
      status: 'BOOKED', // Defaulting to BOOKED as it implies commitment
      target_start_date: null, // User can set later
    })
    .select()
    .single()

  if (jobError || !job) {
    throw new Error(`Failed to create job: ${jobError?.message || 'Unknown error'}`)
  }

  // 3. Create Job Line Items
  if (quote.quote_line_items && quote.quote_line_items.length > 0) {
    const jobLines = quote.quote_line_items.map((item: any) => ({
      job_id: job.id,
      org_id: quote.org_id,
      source_quote_line_id: item.id,
      description: item.description,
      quantity: item.quantity,
      unit: item.unit,
      unit_price_net: item.unit_price_net,
      line_total_net: item.line_total_net,
      status: 'PENDING',
      sort_order: item.sort_order || 0
    }))

    const { error: linesError } = await supabase
      .from('job_line_items')
      .insert(jobLines)

    if (linesError) {
      // Rollback job creation if lines fail? 
      // Supabase RPC transaction would be better, but doing it sequentially for now.
      // If this fails, we have a job with no lines.
      console.error('Failed to create job lines:', linesError)
      throw new Error(`Failed to create job lines: ${linesError.message}`)
    }
  }

  // 4. Update Quote with job_id
  const { error: linkError } = await supabase
    .from('quotes')
    .update({ job_id: job.id })
    .eq('id', quoteId)

  if (linkError) {
    console.error('Failed to link job to quote:', linkError)
    // Non-critical, but annoying for lineage.
  }

  revalidatePath(`/quotes/${quoteId}`)
  revalidatePath('/quotes')
  revalidatePath('/jobs')

  return { success: true, jobId: job.id }
}
