name: Trigger Vercel Deploy Hook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel deploy
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_QMfHAL9jua3vwbqX5MBR9Svaj0fT/YDHt4HxzMk
